---
- hosts: localhost
  remote_user: pi
  gather_facts: no
  tasks:
  - name: Install prerequsiste python3 packages
    pip:
      name:
        - minio==5.0.1
      state: latest

  - name : Copy python script
    template:
      src: "bucket-notification.py"
      dest: "~/bucket-notification.py"

  - name: Kill all bucket notification processes
    shell: "kill $(ps -ef | grep 'bucket-notification.py' | awk '{print $2}')"
    ignore_errors: yes

  - name: Run python script and listen to bucket notifications
    shell: "python3 ~/bucket-notification.py {{ hostname }} {{ mino_user }} {{ minio_pass }} {{ bucket_name }} {{ function_name }} &"
    async: 30
    poll: 0
...