---
- name: create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Docker application
      shell: ssh {{ username }}@{{ host_ip }} 'docker run --name dockerapp -itd {{ image }} "{{ cmd }}"'
