---
- name: create
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Docker
      shell:
        cmd: ssh root@{{ host_ip }} 'apt update'
    - name: Install Dependencies
      shell:
        cmd: ssh root@{{ host_ip }} 'apt install apt-transport-https ca-certificates curl gnupg lsb-release'
    - name: Curl
      shell:
        cmd: ssh root@{{ host_ip }} 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'
    - name: Add GPG key
      shell:
        cmd: ssh root@{{ host_ip }} 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
    - name: Install Docker
      shell:
        cmd: ssh root@{{ host_ip }} 'apt update && apt install docker-ce docker-ce-cli containerd.io'